version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Installing Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Build Storybook
          command: yarn build-storybook
      - store_artifacts:
          path: storybook-static
      - run:
          name: Post Stats to GitHub PR
          command: ./tasks/deployment/comment.sh
          when: on_success

workflows:
  version: 2
  deploy:
    jobs:
      - build